#!/bin/bash

version=$1

docker pull waldronlab/bioconductor_"$version"

mkdir -p "~/.docker-$version-packages"
mkdir -p ~/dockerhome

echo Installed packages will go in host directory "~/.docker-$version-packages"
echo rstudio home directory will be mounted on host directory ~/dockerhome

docker run -e PASSWORD=rstudiopassword \
      -v ~/dockerhome:/home/rstudio/  \
      -v ~/.docker-"$version"-packages:/usr/local/lib/R/host-site-library \
      -p 8787:8787 \
      waldronlab/bioconductor_"$version"

