#!/bin/bash
show_help() {
    echo "Usage: bioc-run [-v version] [-e envtype] [-p port] [-w password] [-d dockerhome] [-l] [-h] [-r] [-q] [-- args...]"
    echo "  -v version    Specify the Bioconductor version (e.g., 'devel', 'RELEASE_X_Y', 'X.Y')."
    echo "  -e envtype    Specify the environment type ('rstudio', 'bash', or 'R'). Default is 'rstudio'."
    echo "  -p port       Specify the port number. Default is 8787."
    echo "  -w password   Specify the RStudio password. Default is 'bioc'."
    echo "  -d dockerhome Specify the Docker home directory. Default is '$HOME/dockerhome'."
    echo "  -l            List all available Bioconductor Docker versions."
    echo "  -h            Show this help message."
    echo "  -q            Quiet mode. Suppress informational messages."
    echo "  -r            Reset the ownership of '$DOCKER_HOME' and '$DOCKER_RPKGS' to '$USERID:$GROUPID'."
    echo "                This option ensures that files in volumes are owned by the same user and group"
    echo "                on the host system."
    echo ""
    echo "Additional arguments after the options will be passed to the environment:"
    echo "  - For 'R' mode: passed as arguments to R (e.g., 'CMD build .' or '--version')"
    echo "  - For 'bash' mode: passed as arguments to bash (e.g., '-c \"command\"')"
    echo "  - For 'rstudio' mode: extra arguments are ignored with a warning"
    echo ""
    echo "For 'R' and 'bash' modes, the current working directory is mounted at /workspace"
    echo "inside the container, allowing you to access local files directly."
    echo ""
    echo "IMPORTANT: Use '--' to stop option parsing if you need to pass arguments that conflict"
    echo "with bioc-run's own options (e.g., -e, -v, -p, -w, -d, -r, -h, -l)."
    echo ""
    echo "Examples:"
    echo "  bioc-run -v devel -e R CMD build ."
    echo "  bioc-run -v devel -e R CMD build myPackage/"
    echo "  bioc-run -v devel -e R --version"
    echo "  bioc-run -v devel -e R -- -e \"print('hello')\"         # Use -- to pass -e to R"
    echo "  bioc-run -v devel -e bash -c 'R CMD build .'"
    echo "  bioc-run -v devel -e bash -- -c 'echo test'           # Use -- to pass -c to bash"
    echo ""
    echo "The \$DOCKER_RPKGS environment variable is optional and used to specify the R packages directory on the host machine."
    echo "If not set, the default is '\$HOME/.docker-\$version-packages'."
    echo "This directory is mounted into the Docker container at /usr/local/lib/R/host-site-library."
    echo "This allows R packages installed in the container to be persisted on the host machine and shared across multiple containers or sessions."
}

list_versions() {
    echo "Fetching available versions from Docker Hub..."
    curl -s https://registry.hub.docker.com/v2/repositories/bioconductor/bioconductor_docker/tags?page_size=100 | jq -r '.results[].name'
}

version=""
envtype="rstudio"
port=8787
password="bioc"
DOCKER_HOME="$HOME/dockerhome"
quiet=false

while getopts ":v:e:p:w:d:lhrq" opt; do
    case ${opt} in
        v )
            version=$OPTARG
            ;;
        e )
            envtype=$OPTARG
            ;;
        p )
            port=$OPTARG
            ;;
        w )
            password=$OPTARG
            ;;
        d )
            DOCKER_HOME=$OPTARG
            ;;
        l )
            list_versions
            exit 0
            ;;
        h )
            show_help
            exit 0
            ;;
        r )
            resetchown="true"
            ;;
        q )
            quiet=true
            ;;
        \? )
            show_help
            exit 1
            ;;
    esac
done

# Shift away the processed options to access remaining arguments
shift $((OPTIND-1))

if [ -z "$version" ]; then
    echo "Error: Version is required. Use the '-v' flag to specify a version. Use the '-l' flag to list available versions or the '-h' flag for examples."
    exit 1
fi

GVER=$(echo "$version" | grep -E "^[3-4]\.[0-9]{1,2}.*")
if [[ -z "${version// }" || ($version != RELEASE_* && $version != devel* && -z "${GVER// }") ]]; then
    echo "Enter either 'devel*', 'X.Y', or 'RELEASE_X_Y' version"
    exit 1
fi

if [ -z "${envtype// }" ]; then
    echo "Empty 'envtype' using default: rstudio"
    envtype="rstudio"
elif [ "$envtype" == "shell" ]; then
    envtype="bash"
fi

if [[ "$envtype" != "rstudio" && "$envtype" != "bash" && "$envtype" != "R" ]]; then
    echo "Enter either 'rstudio', 'bash', or 'R' environment type"
    exit 2
fi

# Warn if extra arguments provided with rstudio mode
if [ "$envtype" == "rstudio" ] && [ $# -gt 0 ]; then
    echo "Warning: Extra arguments provided with rstudio mode will be ignored."
    echo "Arguments: $@"
fi

biocdocker=bioconductor/bioconductor_docker:"$version"
docker pull $biocdocker
DOCKER_RPKGS="$HOME/.docker-$version-packages"
R_LIBS='/usr/local/lib/R/host-site-library:/usr/local/lib/R/site-library:/usr/local/lib/R/library'
mkdir -p "$DOCKER_RPKGS"
mkdir -p "$DOCKER_HOME"

if [ ! -f "$DOCKER_HOME/.Renviron" ]; then
    echo "R_LIBS=$R_LIBS" > $DOCKER_HOME/.Renviron
fi

TOKEN_EXP='GITHUB_[P|T].*'
GPAT=$(grep "$TOKEN_EXP" ~/.Renviron)
GRENV=$(grep "$TOKEN_EXP" $DOCKER_HOME/.Renviron)
if [ ! -z "${GPAT// }" ] && [ -z "${GRENV// }" ]; then
    echo $GPAT >> $DOCKER_HOME/.Renviron
fi

HLIBUSER=$(grep "R_LIBS_USER" ~/.Renviron)
if [ -z "${HLIBENV// }" ]; then
    echo "R_LIBS_USER=/usr/local/lib/R/host-site-library" >> $DOCKER_HOME/.Renviron
fi

copy_config() {
    for arg in "$@"; do
        FILE="$HOME/$arg"
        if [ -e ${FILE} ] && [ ! -e $DOCKER_HOME/$arg ]; then
            cat $FILE > $DOCKER_HOME/$arg
        fi
    done
}

copy_config .Rprofile .gitconfig .inputrc

if [ -n "$resetchown" ]; then
    IFS=':' read USERID GROUPID <<<$(grep "^$(whoami):" /etc/passwd | cut -d':' -f3,4)
    echo ""
    echo "=================================================="
    echo "Resetting ownership of '$DOCKER_HOME' and '$DOCKER_RPKGS' to '$USERID:$GROUPID'"
    echo "=================================================="
    docker run -e PASSWORD=$password \
        -v $DOCKER_HOME:/home/rstudio \
        -v $DOCKER_RPKGS:/usr/local/lib/r/host-site-library \
        -e USERID=$USERID \
        -e GROUPID=$GROUPID \
        -u root \
        $biocdocker \
        bash -c 'chown -R $USERID:$GROUPID /home/rstudio /usr/local/lib/r/host-site-library'
        exit
fi

if [ "$quiet" = false ]; then
    echo ""
    echo "=================================================="
    echo "Installed packages will go in host directory: $DOCKER_RPKGS"
    echo "RStudio home directory will be mounted on host directory: $DOCKER_HOME"
    echo "NOTE. These directories need to be writable by group with GID 1000"
    echo "corresponding to rstudio user in the containers."
    echo "This will be forced in this script."
    echo "=================================================="
    echo ""
fi

docker run --rm \
      -e USERID=$UID \
      -v $DOCKER_HOME:/home/rstudio \
      -v $DOCKER_RPKGS:/usr/local/lib/r/host-site-library \
      -u root \
      $biocdocker \
      bash -c 'chown -R $USERID:1000 /home/rstudio /usr/local/lib/r/host-site-library'

if [ "$envtype" == "rstudio" ]; then
    if [ "$quiet" = false ]; then
        echo "=================================================="
        echo "Open RStudio running Bioconductor version $version at http://localhost:$port"
        echo "Login with username: rstudio and password: $password"
        echo "=================================================="
    fi
    docker run -e PASSWORD=$password \
        -v $DOCKER_HOME:/home/rstudio \
        -v $DOCKER_RPKGS:/usr/local/lib/R/host-site-library \
        -e USERID=$UID \
        -p $port:8787 \
        $biocdocker \
        bash -c '/init'
elif [ "$envtype" == "bash" ]; then
    # On Linux, run as current user to avoid permission issues with mounted workspace
    # On macOS/Windows, run as rstudio user (Docker Desktop handles user mapping)
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        docker run -ti --user $UID:$(id -g) \
            -v $DOCKER_HOME:/home/rstudio \
            -v $DOCKER_RPKGS:/usr/local/lib/R/host-site-library \
            -v "$(pwd)":/workspace \
            -w /workspace \
            $biocdocker bash "$@"
    else
        docker run -ti --user rstudio \
            -v $DOCKER_HOME:/home/rstudio \
            -v $DOCKER_RPKGS:/usr/local/lib/R/host-site-library \
            -v "$(pwd)":/workspace \
            -w /workspace \
            $biocdocker bash "$@"
    fi
elif [ "$envtype" == "R" ]; then
    # On Linux, run as current user to avoid permission issues with mounted workspace
    # On macOS/Windows, run as rstudio user (Docker Desktop handles user mapping)
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        docker run -ti --user $UID:$(id -g) \
            -v $DOCKER_HOME:/home/rstudio \
            -v $DOCKER_RPKGS:/usr/local/lib/R/host-site-library \
            -v "$(pwd)":/workspace \
            -w /workspace \
            $biocdocker R "$@"
    else
        docker run -ti --user rstudio \
            -v $DOCKER_HOME:/home/rstudio \
            -v $DOCKER_RPKGS:/usr/local/lib/R/host-site-library \
            -v "$(pwd)":/workspace \
            -w /workspace \
            $biocdocker R "$@"
    fi
fi
